/**
 * src/app/api/admin/claim-codes/route.ts
 *
 * POST — generate a new claim code for a receiver
 *
 * Purpose:
 * - Admin generates a claim code before a physical visit
 * - Code is stored in VisitLog table linked to the receiver
 * - Receiver uses the code at /claim to fast-track verification
 *
 * Security:
 * - Admin only endpoint
 * - One active code per receiver at a time
 * - Code expires after 90 days
 */

import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { generateClaimCode, getClaimCodeExpiry } from "@/lib/claim-code";

export const dynamic = "force-dynamic";

export async function POST(req: Request) {
  try {
    // 1) Admin only
    const session = await getServerSession(authOptions);
    if (!session?.user?.email) {
      return Response.json({ error: "Not logged in." }, { status: 401 });
    }

    const admin = await prisma.user.findUnique({
      where: { email: session.user.email.toLowerCase() },
      select: { id: true, role: true, name: true },
    });

    if (!admin || admin.role !== "ADMIN") {
      return Response.json({ error: "Admin only." }, { status: 403 });
    }

    // 2) Read receiver ID from request body
    const body = await req.json();
    const receiverId = String(body.receiverId ?? "").trim();

    if (!receiverId) {
      return Response.json({ error: "receiverId is required." }, { status: 400 });
    }

    // 3) Verify receiver exists and has released memories
    const receiver = await prisma.receiver.findUnique({
      where: { id: receiverId },
      select: {
        id: true,
        fullName: true,
        identificationNo: true,
        linkedUserId: true,
        collections: {
          where: {
            items: { some: { status: "RELEASED" } },
          },
          select: { id: true },
        },
      },
    });

    if (!receiver) {
      return Response.json({ error: "Receiver not found." }, { status: 404 });
    }

    if (receiver.linkedUserId) {
      return Response.json(
        { error: "This receiver has already claimed their memory." },
        { status: 400 }
      );
    }

    if (receiver.collections.length === 0) {
      return Response.json(
        { error: "This receiver has no released memories yet." },
        { status: 400 }
      );
    }

    // 4) Invalidate any existing unused claim codes for this receiver
    // Only one active code per receiver at a time
    await prisma.visitLog.updateMany({
      where: {
        receiverId,
        claimCode: { not: null },
        claimCodeExpiresAt: { gt: new Date() },
      },
      data: {
        // Set expiry to now to invalidate existing codes
        claimCodeExpiresAt: new Date(),
      },
    });

    // 5) Generate a new claim code
    const claimCode = generateClaimCode();
    const claimCodeExpiresAt = getClaimCodeExpiry();

    // 6) Create a visit log entry with the claim code
    const visitLog = await prisma.visitLog.create({
      data: {
        receiverId,
        visitDate: new Date(),
        outcome: "OTHER",
        adminNotes: `Claim code generated by admin for receiver ${receiver.fullName}`,
        claimCode,
        claimCodeExpiresAt,
        conductedBy: admin.id,
      },
    });

    return Response.json({
      message: "Claim code generated successfully.",
      claimCode,
      claimCodeExpiresAt: claimCodeExpiresAt.toISOString(),
      visitLogId: visitLog.id,
      receiverName: receiver.fullName,
      receiverNric: receiver.identificationNo,
    });

  } catch (err) {
    console.error("POST /api/admin/claim-codes error:", err);
    return Response.json({ error: "Server error." }, { status: 500 });
  }
}
